const DOLOGIN = 'DOLOGIN';
const SETITEMINDEX = 'SETITEMINDEX';
const SETOFFSET = 'SETOFFSET';
const SETRELOAD = 'SETRELOAD';
const SETCURRENTPAGE = 'SETCURRENTPAGE';
const SETUSERNAME = 'SETUSERNAME';

export default {
    DOLOGIN,
    SETITEMINDEX,
    SETOFFSET,
    SETRELOAD,
    SETCURRENTPAGE,
    SETUSERNAME,
};